#!/bin/sh
echo "=== Firewall rules for port 8443 ==="
uci show firewall | grep -A8 "tg_ws_proxy" || echo "UCI rule not found"
echo ""
echo "=== nftables active rules ==="
nft list ruleset 2>/dev/null | grep -A2 "8443" || echo "nft: no rule for 8443"
echo ""
echo "=== iptables check ==="
iptables -L INPUT -n 2>/dev/null | grep "8443" || echo "iptables: no rule for 8443"
echo ""
echo "=== Port 8443 listening? ==="
netstat -tlnp 2>/dev/null | grep 8443 || ss -tlnp 2>/dev/null | grep 8443 || echo "Nothing listening on 8443"
echo ""
echo "=== tg-ws-proxy process ==="
ps | grep tg-ws | grep -v grep || echo "Process not running"
echo ""
echo "=== /tmp files ==="
ls -lh /tmp/tg-ws* 2>/dev/null || echo "No binary in /tmp yet"
